docs/kmstool.md

Signed-off-by: Alexandra Pirvulescu <alexprv@amazon.com>

docs: Add link to vsock-proxy documentation

---

containers/Dockerfile.al2

Signed-off-by: Petre Eftime <epetre@amazon.com>

containers: cleanup Dockerfile.al2

---

docs/kmstool.md

docs: correct typo

---

bin/kmstool-enclave-cli/README.md

*Correcting typo in kmstool-enclave-cli README*

Correct typo in kmstool-enclave-cli README

---

docs/kmstool.md

Clarified some issues around regions and added a troubleshooting guide.

kmstool: add troubleshooting

---

include/aws/nitro_enclaves/kms.h
source/kms.c
tests/kms_test.c

Remove unimplemented structures and parameters.

Remove unused APIs

---

CMakeLists.txt
containers/Dockerfile.al2
include/aws/nitro_enclaves/kms.h
include/aws/nitro_enclaves/nitro_enclaves.h

Signed-off-by: Petre Eftime <epetre@amazon.com>

Add additional documentation and build with doxygen

---

README.md

The current command presented in `README.md` is malformed. This PR fixes it. Tested by running the exact docker command and looking for the outputs inside of the container.

README.md: Fix `docker build` example invocation

---

source/rest.c

Signed-off-by: Petre Eftime <epetre@amazon.com>
*Issue #, if available:* #49
Tentatively fix #49, as I was not able to reproduce the issue.

rest: initialize tls_connections_options

---

docs/kmstool.md

Signed-off-by: Daniela-Liliana Dragan <ddraga@amazon.com>
*Description of changes:* Update command that creates the KMS CMK for production mode to use the production like policy (enclave-policy.json). 

Fix documentation for production kmstool

---

CHANGELOG.md
CMakeLists.txt
README.md

Prepare 0.2.1 release

---

source/attestation.c

The description of attestation_doc was wrong.

fix a comment in attestation.c

---

README.md
containers/Dockerfile.al2

Signed-off-by: Alexandru Ciobotaru <alcioa@amazon.com>

deps: update dependencies

---

containers/Dockerfile.al2

Improve the overall build time and reduce the kmstool-enclave image size.

Build improvements

---

bin/kmstool-enclave-cli/README.md

*Description of changes:
* Updated readme for kmstool-enclave-cli to support new operation flags `decrypt` and `genkey`.

Updated kmstool-enclave-cli readme

---

CHANGELOG.md

Update CHANGELOG (retroactively). 

prepare 0.3.2 release

---

README.md
containers/Dockerfile.al2
source/cms.c

This PR updates outdated dependencies and reduces build time.

Update SDK dependencies

---

containers/Dockerfile.al2

containers: update rust version to 1.63

---

README.md
containers/Dockerfile.al2

update aws-nitro-enclaves-nsm-api version

---

.github/workflows/docker-run-tests.yml

This commit adds a Github action configuration to build and run tests for the SDK.

Add CI workflow for tests

---

CHANGELOG.md

Create changelog entries for 0.4.0, 0.4.1, and 0.4.2.

Update changelog to 0.4.2
